import type { Snapshot } from "./types";
const now = Math.floor(Date.now() / 1000);
export const demoData: Snapshot = {
  role: "owner",
  labs: [
    {
      id: "lab-home",
      name: "Home lab",
      description: "A little space for big ideas.",
    },
    {
      id: "lab-edge",
      name: "Edge experiments",
      description: "Small devices. Interesting possibilities.",
    },
  ],
  nodes: [
    {
      id: "n1",
      lab_id: "lab-home",
      name: "Atlas workstation",
      platform: "Linux",
      arch: "x86_64",
      cpus: 16,
      memory_mb: 65536,
      cpu_usage: 32,
      memory_used_mb: 19456,
      last_seen: now,
      docker: true,
      revoked: false,
    },
    {
      id: "n2",
      lab_id: "lab-home",
      name: "Mac mini",
      platform: "macOS",
      arch: "aarch64",
      cpus: 10,
      memory_mb: 16384,
      cpu_usage: 18,
      memory_used_mb: 6144,
      last_seen: now,
      docker: true,
      revoked: false,
    },
    {
      id: "n3",
      lab_id: "lab-home",
      name: "Raspberry Pi 5",
      platform: "Linux",
      arch: "aarch64",
      cpus: 4,
      memory_mb: 8192,
      cpu_usage: 8,
      memory_used_mb: 1024,
      last_seen: now,
      docker: true,
      revoked: false,
    },
    {
      id: "n4",
      lab_id: "lab-home",
      name: "ThinkPad",
      platform: "Linux",
      arch: "x86_64",
      cpus: 8,
      memory_mb: 16384,
      cpu_usage: 0,
      memory_used_mb: 0,
      last_seen: now - 86400,
      docker: true,
      revoked: false,
    },
  ],
  workspaces: [
    {
      id: "w1",
      lab_id: "lab-home",
      node_id: "n1",
      name: "Deep learning playground",
      template: "jupyter",
      cpus: 4,
      memory_mb: 8192,
      status: "running",
      created_at: now - 14400,
      last_used: now,
      error: "",
      network: false,
    },
    {
      id: "w2",
      lab_id: "lab-home",
      node_id: "n2",
      name: "Weekend project",
      template: "code",
      cpus: 2,
      memory_mb: 4096,
      status: "running",
      created_at: now - 9000,
      last_used: now,
      error: "",
      network: false,
    },
    {
      id: "w3",
      lab_id: "lab-home",
      node_id: "n3",
      name: "Sensor experiments",
      template: "terminal",
      cpus: 1,
      memory_mb: 1024,
      status: "stopped",
      created_at: now - 86400,
      last_used: now - 4000,
      error: "",
      network: false,
    },
  ],
  events: [
    {
      id: "e1",
      lab_id: "lab-home",
      message: "Deep learning playground started",
      at: now - 180,
      kind: "workspace",
    },
    {
      id: "e2",
      lab_id: "lab-home",
      message: "Mac mini connected to Home lab",
      at: now - 780,
      kind: "node",
    },
    {
      id: "e3",
      lab_id: "lab-home",
      message: "Sensor experiments stopped",
      at: now - 3600,
      kind: "workspace",
    },
  ],
  settings: {
    name: "My CloudLab",
    session_hours: 12,
    idle_minutes: 60,
    max_workspaces: 12,
    default_cpus: 2,
    default_memory_mb: 2048,
    allow_network: false,
    public_url: "",
  },
  access: [],
};
