#!/usr/bin/env python3
"""Plan or install CloudLab on a dedicated cloud VM. Standard library only.

Run without --apply to generate files only. See docs/cloud-access.md.
"""
import argparse
import http.cookiejar
import ipaddress
import json
import os
import platform
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROVIDERS = ("auto", "aws", "gcp", "azure", "digitalocean", "other")
METADATA = "http://169.254.169.254"
SERVICE = "cloudlab-cloud-agent.service"
AGENT_DIR = Path("/var/lib/cloudlab-cloud-agent")
ENROLLMENT_FILE = Path("/etc/cloudlab-cloud-agent.env")


class SetupError(Exception):
    pass


class NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        raise SetupError("A local setup endpoint attempted a redirect.")


def public_ipv4(value):
    try:
        address = ipaddress.IPv4Address(value.strip())
    except ipaddress.AddressValueError as error:
        raise SetupError("Enter a public IPv4 address without a port or URL.") from error
    if not address.is_global or address.is_multicast or address.is_reserved:
        raise SetupError("Use the VM's routable public IPv4 address, not its private address.")
    return str(address)


def metadata(path, method="GET", headers=None):
    # Only fixed link-local paths below are requested. Never read IAM credentials,
    # instance user-data, environment proxies, or an external 'what is my IP' site.
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}), NoRedirect())
    request = urllib.request.Request(METADATA + path, method=method, headers=headers or {})
    with opener.open(request, timeout=2) as response:
        payload = response.read(4097)
        if len(payload) > 4096:
            raise SetupError("Metadata response was too large.")
        return payload.decode("ascii").strip()


def detect_ip(provider, fetch=metadata):
    providers = PROVIDERS[1:-1] if provider == "auto" else (provider,)
    for candidate in providers:
        try:
            if candidate == "aws":
                token = fetch("/latest/api/token", method="PUT",
                              headers={"X-aws-ec2-metadata-token-ttl-seconds": "60"})
                if not token or not re.fullmatch(r"[\x21-\x7e]+", token):
                    raise SetupError("Invalid metadata token")
                value = fetch("/latest/meta-data/public-ipv4",
                              headers={"X-aws-ec2-metadata-token": token})
            elif candidate == "gcp":
                value = fetch("/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip",
                              headers={"Metadata-Flavor": "Google"})
            elif candidate == "azure":
                value = fetch("/metadata/instance/network/interface/0/ipv4/ipAddress/0/publicIpAddress"
                              "?api-version=2025-04-07&format=text", headers={"Metadata": "true"})
            elif candidate == "digitalocean":
                # Prefer an attached Reserved IP over the Droplet's original IP.
                try:
                    value = public_ipv4(fetch("/metadata/v1/reserved_ip/ipv4/ip_address"))
                except (OSError, ValueError, SetupError):
                    value = fetch("/metadata/v1/interfaces/public/0/ipv4/address")
            else:
                continue
            return candidate, public_ipv4(value)
        except (OSError, ValueError, SetupError):
            continue
    raise SetupError("No public IP was detected. Attach a public/static IPv4 address and pass --public-ip ADDRESS.")


def addresses(ip, domain=None):
    ip = public_ipv4(ip)
    if domain:
        domain = domain.lower().strip().rstrip(".")
        if len(domain) > 190 or not re.fullmatch(
            r"(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}", domain
        ):
            raise SetupError("Domain must be a DNS suffix such as cloud.example.com, without a URL or wildcard.")
    suffix = domain or ip.replace(".", "-") + ".sslip.io"
    return {"ip": ip, "suffix": suffix, "dashboard": "https://lab." + suffix,
            "workspaces": "https://{workspace}." + suffix, "dns": "custom" if domain else "sslip.io"}


def caddyfile(plan):
    return f'''# Generated by CloudLab. Public HTTP only redirects; credentials use HTTPS.
{{
    auto_https disable_redirects
    on_demand_tls {{
        ask http://coordinator:8088/api/tls/allow
    }}
}}

:80 {{
    @ip host {plan["ip"]}
    handle @ip {{
        redir {plan["dashboard"]} 308
    }}
    @known host lab.{plan["suffix"]} *.{plan["suffix"]}
    handle @known {{
        redir https://{{host}}{{uri}} 308
    }}
    handle {{
        respond "Unknown CloudLab address" 404
    }}
}}

{plan["dashboard"]} {{
    @internal path /api/tls/*
    respond @internal 404
    reverse_proxy coordinator:8088
}}

https:// {{
    tls {{
        on_demand
    }}
    @workspace host *.{plan["suffix"]}
    handle @workspace {{
        reverse_proxy coordinator:8089
    }}
    handle {{
        respond "Unknown CloudLab workspace" 404
    }}
}}
'''


def compose_config(plan, root, output):
    # JSON is valid Compose YAML and preserves spaces/quotes in paths.
    def compose_path(path):
        return str(path).replace("$", "$$")
    return {"name": "cloudlab-cloud", "services": {
        "coordinator": {
            "build": {"context": compose_path(root)}, "restart": "unless-stopped",
            "ports": ["127.0.0.1:8088:8088"],
            "environment": {"CLOUDLAB_APP_URL": plan["workspaces"], "CLOUDLAB_PUBLIC_URL": plan["dashboard"]},
            "volumes": ["coordinator-data:/data"], "read_only": True,
            "tmpfs": ["/tmp:rw,noexec,nosuid,size=64m"], "cap_drop": ["ALL"],
            "security_opt": ["no-new-privileges:true"], "pids_limit": 128,
            "mem_limit": "1g", "cpus": 2,
        },
        "gateway": {
            "image": "caddy:2-alpine", "restart": "unless-stopped", "depends_on": ["coordinator"],
            "ports": ["80:80", "443:443"],
            "volumes": [{"type": "bind", "source": compose_path(output / "Caddyfile"),
                         "target": "/etc/caddy/Caddyfile", "read_only": True},
                        "caddy-data:/data", "caddy-config:/config"],
            "read_only": True, "tmpfs": ["/tmp:rw,noexec,nosuid,size=32m"],
            "cap_drop": ["ALL"], "cap_add": ["NET_BIND_SERVICE"],
            "security_opt": ["no-new-privileges:true"], "pids_limit": 128, "mem_limit": "512m",
        },
    }, "volumes": {"coordinator-data": {}, "caddy-data": {}, "caddy-config": {}}}


def agent_service(groups):
    return f'''# Managed by scripts/cloud-access.py
[Unit]
Description=CloudLab cloud compute node
After=network-online.target docker.service
Wants=network-online.target docker.service

[Service]
Type=simple
DynamicUser=yes
SupplementaryGroups={" ".join(groups)}
StateDirectory=cloudlab-cloud-agent
StateDirectoryMode=0700
Environment=DOCKER_HOST=unix:///var/run/docker.sock
EnvironmentFile=-{ENROLLMENT_FILE}
ExecStart=/usr/local/lib/cloudlab-cloud/cloudlab agent --coordinator http://127.0.0.1:8088 --data-dir {AGENT_DIR}
Restart=always
RestartSec=5
UMask=0077
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes

[Install]
WantedBy=multi-user.target
'''


def write_file(path, value, mode=0o600):
    # Replace atomically and do not follow a pre-existing destination symlink.
    fd, temporary_name = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        if hasattr(os, "fchmod"):
            os.fchmod(fd, mode)
        else:
            os.chmod(temporary, mode)
        with os.fdopen(fd, "w") as stream:
            stream.write(value)
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def run(args, capture=False):
    result = subprocess.run([str(a) for a in args], check=True, text=True,
                            stdout=subprocess.PIPE if capture else None)
    return result.stdout.strip() if capture else ""


def compose(output, *args, capture=False):
    # Do not inherit a remote Docker context: this installs on the current VM.
    return run(["docker", "--host", "unix:///var/run/docker.sock", "compose", "--project-name", "cloudlab-cloud",
                "--file", output / "compose.yaml", *args], capture)


def preflight():
    if platform.system() != "Linux" or not Path("/run/systemd/system").is_dir():
        raise SetupError("Automatic installation needs a Linux VM with systemd (Ubuntu 24.04+ or Debian 12+). Planning works on any OS.")
    if platform.machine().lower() not in ("aarch64", "arm64", "x86_64", "amd64"):
        raise SetupError("Automatic installation supports 64-bit x86 or ARM cloud VMs.")
    if os.geteuid() != 0:
        raise SetupError("Run --apply with sudo on the cloud VM; it installs a compute service and HTTPS gateway.")
    import grp
    libc, version = platform.libc_ver()
    if libc != "glibc" or tuple(int(v) for v in version.split(".")[:2]) < (2, 36):
        raise SetupError("The bundled Linux agent needs glibc 2.36+. Use Ubuntu 24.04+ or Debian 12+.")
    if not shutil.which("docker") or not Path("/var/run/docker.sock").exists():
        raise SetupError("Install Docker Engine and its Compose plugin on this VM first. See docs/cloud-access.md.")
    try:
        grp.getgrnam("docker")
    except KeyError as error:
        raise SetupError("The standard Docker Engine 'docker' group is required for the compute service.") from error
    run(["docker", "--host", "unix:///var/run/docker.sock", "compose", "version"], capture=True)
    run(["docker", "--host", "unix:///var/run/docker.sock", "info"], capture=True)


class LocalAPI:
    def __init__(self):
        self.opener = urllib.request.build_opener(urllib.request.ProxyHandler({}), NoRedirect(),
                         urllib.request.HTTPCookieProcessor(http.cookiejar.CookieJar()))

    def call(self, path, body=None):
        request = urllib.request.Request("http://127.0.0.1:8088/api" + path,
                    data=None if body is None else json.dumps(body).encode(),
                    headers={"Content-Type": "application/json", "X-CloudLab-Client": "web"})
        with self.opener.open(request, timeout=5) as response:
            return json.loads(response.read(1024 * 1024))


def wait_for(check, message, seconds=90):
    deadline = time.monotonic() + seconds
    while time.monotonic() < deadline:
        try:
            if check():
                return
        except (OSError, ValueError):
            pass
        time.sleep(2)
    raise SetupError(message)


def prepare(output):
    # Validate/build before replacing the running stack or agent.
    compose(output, "config", "--quiet")
    compose(output, "run", "--rm", "--no-deps", "gateway", "caddy", "validate",
            "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile")
    compose(output, "build", "coordinator")
    for template in ("terminal", "jupyter", "code"):
        run(["docker", "--host", "unix:///var/run/docker.sock", "build", "-f",
             ROOT / "containers" / (template + ".Dockerfile"), "-t", "cloudlab/" + template + ":2", ROOT])


def install(output, plan):
    import grp
    compose(output, "up", "-d", "--remove-orphans")
    # Existing bind mounts can retain the old file after an atomic replacement.
    compose(output, "up", "-d", "--force-recreate", "gateway")
    api = LocalAPI()
    wait_for(lambda: api.call("/health").get("status") == "ok",
             "Gateway started, but the coordinator is not ready. Inspect the Compose logs.")
    instance_id = api.call("/health")["instance_id"]
    owner = compose(output, "exec", "-T", "coordinator", "cat", "/data/admin-token", capture=True)
    api.call("/login", {"token": owner})
    try:
        snapshot = api.call("/state")
        if snapshot["settings"]["public_url"] != plan["dashboard"]:
            raise SetupError("The coordinator reports a different public address. Check for an existing installation on port 8088.")
        if not (AGENT_DIR / "credentials.json").exists():
            lab = next((lab for lab in snapshot["labs"] if lab["name"] == "Cloud workspace"), None)
            if lab is None:
                lab = api.call("/labs", {"name": "Cloud workspace", "description": "Hosted on this cloud VM."})
            enrollment = api.call("/enrollments", {"lab_id": lab["id"], "name": "Cloud VM"})
            if not re.fullmatch(r"[a-f0-9]{64}", enrollment["token"]):
                raise SetupError("Invalid enrollment response")
            write_file(ENROLLMENT_FILE, "CLOUDLAB_ENROLLMENT=" + enrollment["token"] + "\n")
        binary_dir = Path("/usr/local/lib/cloudlab-cloud")
        binary_dir.mkdir(parents=True, exist_ok=True)
        compose(output, "cp", "coordinator:/usr/local/bin/cloudlab", binary_dir / "cloudlab.new")
        os.chown(binary_dir / "cloudlab.new", 0, 0)
        (binary_dir / "cloudlab.new").chmod(0o755)
        (binary_dir / "cloudlab.new").replace(binary_dir / "cloudlab")
        groups = ["docker"]
        for group in ("video", "render"):
            try:
                grp.getgrnam(group)
                groups.append(group)
            except KeyError:
                pass
        write_file(Path("/etc/systemd/system") / SERVICE, agent_service(groups), 0o644)
        run(["systemctl", "daemon-reload"])
        run(["systemctl", "enable", SERVICE])
        run(["systemctl", "restart", SERVICE])

        def ready():
            path = AGENT_DIR / "credentials.json"
            if not path.exists():
                return False
            node_id = json.loads(path.read_text())["id"]
            return any(n["id"] == node_id and not n["revoked"] and n["docker"]
                       and n["last_seen"] > time.time() - 30 for n in api.call("/state")["nodes"])
        wait_for(ready, "The dashboard is running, but the compute node is not ready. Run: sudo journalctl -u " + SERVICE)
        ENROLLMENT_FILE.unlink(missing_ok=True)
    finally:
        api.call("/logout", {})
    write_file(output / "deployment.json", json.dumps(plan, indent=2) + "\n")
    # Verify the public origin using normal certificate validation; never claim
    # success from a local health check or disable TLS verification.
    public = urllib.request.build_opener(urllib.request.ProxyHandler({}), NoRedirect())

    def https_ready():
        with public.open(plan["dashboard"] + "/api/health", timeout=8) as response:
            health = json.loads(response.read(4096))
            return health.get("status") == "ok" and health.get("instance_id") == instance_id
    wait_for(https_ready,
             "The lab and compute node are running locally. Public HTTPS is not ready: check inbound TCP 80/443, DNS and gateway logs, then rerun setup.", seconds=120)


def write_plan(output, plan):
    output.mkdir(parents=True, exist_ok=True, mode=0o700)
    write_file(output / "compose.yaml", json.dumps(compose_config(plan, ROOT, output), indent=2) + "\n")
    write_file(output / "Caddyfile", caddyfile(plan))
    write_file(output / "agent.service", agent_service(["docker"]))
    write_file(output / "plan.json", json.dumps(plan, indent=2) + "\n")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--provider", choices=PROVIDERS, default="auto")
    parser.add_argument("--public-ip", help="VM public/static IPv4; skips metadata detection")
    parser.add_argument("--domain", help="Optional domain suffix; point lab and wildcard A records to the IP first")
    parser.add_argument("--output", type=Path, help="Configuration directory (defaults to .cloudlab/cloud-access for installs, cloud-access-plan for plans)")
    parser.add_argument("--apply", action="store_true", help="Build and start dashboard, HTTPS gateway and local compute service")
    args = parser.parse_args(argv)
    if args.apply:
        preflight()
    provider, ip = (args.provider, public_ipv4(args.public_ip)) if args.public_ip else detect_ip(args.provider)
    plan = addresses(ip, args.domain)
    plan["provider"] = provider
    output = (args.output or ROOT / ".cloudlab" / ("cloud-access" if args.apply else "cloud-access-plan")).resolve()
    previous_path = output / "deployment.json"
    if args.apply and previous_path.exists() and not args.public_ip:
        previous = json.loads(previous_path.read_text())
        if previous["ip"] != ip:
            raise SetupError("The public IP changed. Use a reserved/static IP, then rerun with --public-ip to update deliberately. Remote nodes may need pairing again.")
    print("Dashboard: " + plan["dashboard"])
    print("Public IP entry: http://" + ip + " → HTTPS dashboard")
    print("Workspace addresses: " + plan["workspaces"])
    print("DNS: " + ("your domain" if args.domain else "sslip.io (public IP-based DNS; no DNS account required)"))
    print("Allow inbound TCP 80 and 443 in the cloud firewall and VM firewall.")
    print("Setup files: " + str(output))
    if args.apply:
        # A failed build/validation leaves the previous deployment files intact.
        output.mkdir(parents=True, exist_ok=True, mode=0o700)
        with tempfile.TemporaryDirectory(prefix="prepare-", dir=output) as staged:
            write_plan(Path(staged), plan)
            prepare(Path(staged))
        write_plan(output, plan)
        install(output, plan)
        print("HTTPS dashboard verified; the cloud compute node is online. Open " + plan["dashboard"])
        print("Read your owner key privately on this VM with:")
        print(shlex.join(["sudo", "docker", "--host", "unix:///var/run/docker.sock", "compose", "-p", "cloudlab-cloud",
                          "-f", str(output / "compose.yaml"), "exec", "coordinator", "cat", "/data/admin-token"]))
    else:
        write_plan(output, plan)
        print("Plan only. Nothing was installed or started. Add --apply on the cloud VM to install.")


if __name__ == "__main__":
    try:
        main()
    except (SetupError, OSError, ValueError, subprocess.CalledProcessError) as error:
        # Do not dump API responses, command output, enrollment keys or owner keys.
        print("CloudLab setup: " + (str(error) if isinstance(error, SetupError) else
              "A setup operation failed (" + type(error).__name__ + "). Check the preceding build/service output and docs/cloud-access.md."), file=sys.stderr)
        sys.exit(1)
